# Generated by Django 3.2.16 on 2024-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240219_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
